<script lang="ts">
    let svg;
    function start() {
        svg.classList.add("active");
    }
    function reset() {
        svg.classList.remove("active");
    }
</script>

<div class="wrapper">
    <svg
        bind:this={svg}
        on:load={start}
        viewBox="0 0 512 512"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
    >
        <g filter="url(#filter0_d_57_329)">
            <g clip-path="url(#clip0_57_329)">
                <rect
                    x="50"
                    y="50"
                    width="412"
                    height="412"
                    rx="90"
                    fill="#1C1C1E"
                    class="svg-elem-1"
                />
                <path
                    d="M90 120C90 103.431 103.431 90 120 90H156C205.706 90 246 130.294 246 180V319C246 335.569 232.569 349 216 349H180C130.294 349 90 308.706 90 259V120Z"
                    fill="#457B9D"
                    class="svg-elem-2"
                />
                <path
                    d="M266 129.75C266 107.797 283.797 90 305.75 90H408.75C416.068 90 422 95.9322 422 103.25V103.25C422 125.203 404.203 143 382.25 143H279.25C271.932 143 266 137.068 266 129.75V129.75Z"
                    fill="#D02D4A"
                    class="svg-elem-3"
                />
                <path
                    d="M90 395.5C90 380.864 101.864 369 116.5 369H232.75C240.068 369 246 374.932 246 382.25V382.25C246 404.203 228.203 422 206.25 422H116.5C101.864 422 90 410.136 90 395.5V395.5Z"
                    fill="#A8DADC"
                    class="svg-elem-4"
                />
                <path
                    d="M266 193C266 176.431 279.431 163 296 163H332C381.706 163 422 203.294 422 253V344C422 387.078 387.078 422 344 422V422C300.922 422 266 387.078 266 344V193Z"
                    fill="#F1FAEE"
                    class="svg-elem-5"
                />
            </g>
        </g>
        <defs>
            <filter
                id="filter0_d_57_329"
                x="-10"
                y="-6"
                width="532"
                height="532"
                filterUnits="userSpaceOnUse"
                color-interpolation-filters="sRGB"
            >
                <feFlood flood-opacity="0" result="BackgroundImageFix" />
                <feColorMatrix
                    in="SourceAlpha"
                    type="matrix"
                    values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    result="hardAlpha"
                />
                <feOffset dy="4" />
                <feGaussianBlur stdDeviation="5" />
                <feComposite in2="hardAlpha" operator="out" />
                <feColorMatrix
                    type="matrix"
                    values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"
                />
                <feBlend
                    mode="normal"
                    in2="BackgroundImageFix"
                    result="effect1_dropShadow_57_329"
                />
                <feBlend
                    mode="normal"
                    in="SourceGraphic"
                    in2="effect1_dropShadow_57_329"
                    result="shape"
                />
            </filter>
            <clipPath id="clip0_57_329">
                <rect
                    x="50"
                    y="50"
                    width="412"
                    height="412"
                    rx="90"
                    fill="white"
                    class="svg-elem-6"
                />
            </clipPath>
        </defs>
    </svg>
</div>

<style global>
    .wrapper {
        grid-row: 1;
        grid-column: 2;
        z-index: 2;
    }
    /***************************************************
 * Generated by SVG Artista on 12/3/2022, 6:24:59 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

    svg .svg-elem-1 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 0.8s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 0.8s;
    }

    svg.active .svg-elem-1 {
        fill: rgb(28, 28, 30);
    }

    svg .svg-elem-2 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 0.9s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 0.9s;
    }

    svg.active .svg-elem-2 {
        fill: rgb(69, 123, 157);
    }

    svg .svg-elem-3 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1s;
    }

    svg.active .svg-elem-3 {
        fill: rgb(208, 45, 74);
    }

    svg .svg-elem-4 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1.1s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1.1s;
    }

    svg.active .svg-elem-4 {
        fill: rgb(168, 218, 220);
    }

    svg .svg-elem-5 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1)
            1.2000000000000002s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1)
            1.2000000000000002s;
    }

    svg.active .svg-elem-5 {
        fill: rgb(241, 250, 238);
    }

    svg .svg-elem-6 {
        fill: transparent;
        -webkit-transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1.3s;
        transition: fill 1.2s cubic-bezier(0.215, 0.61, 0.355, 1) 1.3s;
    }

    svg.active .svg-elem-6 {
        fill: rgb(255, 255, 255);
    }
</style>
